apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: portfolio
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'portfolio-app'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['portfolio-backend-service.portfolio.svc.cluster.local:8080']
