apiVersion: v1
kind: Service
metadata:
  name: portfolio-backend-service
  namespace: portfolio
spec:
  selector:
    app: portfolio-backend
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort