apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-backend
  namespace: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-backend
  template:
    metadata:
      labels:
        app: portfolio-backend
    spec:
      containers:
        - name: backend
          image: portfolio-backend:1.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: portfolio-config
            - secretRef:
                name: portfolio-secrets
