apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: portfolio-secrets
                  key: SPRING_RABBITMQ_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: SPRING_RABBITMQ_PASS
          ports:
            - name: amqp
              containerPort: 5672
            - name: http
              containerPort: 15672
